#!/usr/bin/env python3
"""Canonical Grafana dashboard generator. Run --check to reject stale JSON."""
import argparse
import json
from pathlib import Path
import sys
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]


def dashboard(contract):
    def text(panel_id, title, content, y, height=4):
        return {"id": panel_id, "title": title, "type": "text", "gridPos": {"x": 0, "y": y, "w": 24, "h": height}, "options": {"mode": "markdown", "content": content}}

    panels = [text(1, "CI observations · source evidence stays authoritative", "Fixed metric scope: **ci / test**, trace repository: **YRootLab/OnMaru-backend**. Duration panels show exported histogram snapshot means, not percentiles or three-run comparisons. Outcome/quality/work are gauges; never interpret scrape samples as cumulative run totals. Missing data is unknown. Traces reconstruct observed job windows; workflow wall-clock, queue and critical path are unavailable.\n\nCollector operational panels separately observe downstream failures and queue pressure on this local Collector. Open a trace, then the run ID's **Actions run** or **Manifest artifacts** link. The latter opens the artifact list: match the persisted evidence digest. Pre-Collector Toolkit delivery status remains consumer-local; see the boundary notice.", 0, 5)]
    metric_count = sum(item["language"] == "promql" for item in contract["queries"])
    notice_y = 5 + 8 * ((metric_count + 1) // 2)
    metric_index = trace_index = 0
    for item in contract["queries"]:
        trace = item["language"] == "traceql"
        source = {"type": "tempo" if trace else "prometheus", "uid": "local-tempo" if trace else "local-prometheus"}
        target = {"refId": "A", "datasource": source}
        if trace:
            target.update(query=item["query"], queryType="traceql", tableType="spans", limit=20, spss=1)
        else:
            target.update(expr=item["query"], editorMode="code", range=True, instant=False, legendFormat="__auto")
        panel = {"id": item["panel_id"], "title": item["title"], "description": item["description"], "type": "table" if trace else "timeseries", "datasource": source, "targets": [target], "gridPos": {"x": 0 if trace else metric_index % 2 * 12, "y": notice_y + 5 + trace_index * 10 if trace else 5 + metric_index // 2 * 8, "w": 24 if trace else 12, "h": 10 if trace else 8}, "fieldConfig": {"defaults": {"unit": item["unit"], "noValue": "No telemetry", "custom": {}}, "overrides": []}, "options": {"showHeader": True} if trace else {"legend": {"displayMode": "list", "placement": "bottom"}, "tooltip": {"mode": "single"}}}
        if trace:
            panes = {"trace": {"datasource": "local-tempo", "queries": [{"refId": "A", "queryType": "traceql", "query": "TRACE_ID"}], "range": {"from": "now-1h", "to": "now"}}}
            trace_url = "/explore?schemaVersion=1&panes=" + quote(json.dumps(panes, separators=(",", ":")), safe="").replace("TRACE_ID", "${__value.raw:percentencode}")
            run_url = "https://github.com/YRootLab/OnMaru-backend/actions/runs/${__value.raw:percentencode}"
            panel["fieldConfig"]["overrides"] = [
                {"matcher": {"id": "byName", "options": "traceIdHidden"}, "properties": [{"id": "custom.hideFrom", "value": {"viz": False}}, {"id": "displayName", "value": "Trace ID"}, {"id": "links", "value": [{"title": "Tempo trace", "url": trace_url, "targetBlank": True}]}]},
                {"matcher": {"id": "byName", "options": "cicd.pipeline.run.id"}, "properties": [{"id": "links", "value": [{"title": "Actions run", "url": run_url, "targetBlank": True}, {"title": "Manifest artifacts", "url": run_url + "#artifacts", "targetBlank": True}]}]},
            ]
        panels.append(panel)
        if trace:
            trace_index += 1
        else:
            metric_index += 1
    panels.append(text(16, "Delivery boundary · Toolkit → Collector → backends", "**Collector panels measure downstream exporter activity, not the pre-Collector Toolkit HTTP path.** Toolkit `ExportResult.status`, `reason`, `pending_batches`, `terminal_partial_batches` and acknowledgement timestamps remain consumer-local and cannot be observed through the same failed channel. Preserve those diagnostics and the original CI conclusion independently.\n\nQueue utilization and in-flight requests are backlog/lag proxies, not seconds. Exact end-to-end lag = acknowledgement − source completion; unavailable timestamps mean unknown. The Prometheus pull exporter's accepted-point count is not proof of scrape/retention. Self-scrape must be up before zero observed failures is shown; an idle never-used exporter has no failure baseline.", notice_y, 5))
    return {"id": None, "uid": "toolkit-ci-benchmark", "title": "Toolkit CI benchmark observations", "description": "Generated by scripts/build_ci_dashboard.py from observability/queries/ci-benchmark.json. Evidence and telemetry contracts v1.", "tags": ["ci", "pipeline-toolkit"], "timezone": "utc", "schemaVersion": 39, "version": 1, "editable": False, "refresh": "30s", "time": {"from": "now-1h", "to": "now"}, "timepicker": {"refresh_intervals": ["30s", "1m", "5m"]}, "templating": {"list": []}, "annotations": {"list": []}, "links": [], "panels": sorted(panels, key=lambda panel: panel["id"])}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = json.loads((ROOT / "observability/queries/ci-benchmark.json").read_text())
    result = json.dumps(dashboard(contract), indent=2, ensure_ascii=False) + "\n"
    path = ROOT / "observability/dashboards/ci-benchmark.json"
    if args.check:
        if not path.is_file() or path.read_text() != result:
            print("Dashboard is stale; run python3 scripts/build_ci_dashboard.py", file=sys.stderr)
            return 1
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
